blog/urls.py
from django.views.generic import ListView, DetailView
from django.urls import path
from .models import Post

urlpatterns = [
    path('',
        ListView.as_view(
            queryset=
            Post.objects.all().order_by("-date")[:25],
            template_name="blog.html"
            )
        ),
    path('<int:pk>/',
        DetailView.as_view(
            model=Post,
            template_name="post.html"
            )
         ),
]

mysite/the_rent/the_rent/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('blog/', include('blog.urls')),
    path('polls', include('polls.urls')),
    path('', include("django.contrib.auth.urls")),
    path('', include("user_auth.urls")),

]

user_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('login', views.user_login, name='login'),
    path('authenticate_user/user/<str:username>/', views.show_user, name='show_user'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
]

user_auth/models.py
from django.db import models

# Create your models here.

user_auth/forms.py
from django import forms


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=100)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

user_auth/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import RegistrationForm, LoginForm
from django.urls import reverse
from . import views
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


# Create your views here.
'''def user_login(request):
    return render(request, 'authentication/login.html')'''


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('polls')
            else:
                return redirect(form=LoginForm())
    else:
        return render(request, 'authentication/login.html', {})


def authenticate_user(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(reverse('polls:index'))


def show_user(request, username):
    user = User.objects.get(username=username)
    return render(request, 'authentication/user.html', {
        "username": user.username,
        "password": user.password
    })


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            first_name = form.cleaned_data['first_name']
            user = User.objects.create_user(username=username, password=password, first_name=first_name)
            return HttpResponseRedirect(reverse('polls:index'))
    else:
        form = RegistrationForm()

    return render(request, 'registration/registration.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('user_auth:login')

user_auth/templates/authentication/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossorigin="anonymous">
    <meta charset="utf8"/>
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<h1> Login as User </h1>

<form method="POST" action="{% url 'user_auth:authenticate_user' %}">
  {% csrf_token %}

  <label for="id_username">Username</label>
  <input type="text" name="username" id="id_username" placeholder="User" required>
  <br/><br/>

  <label for="id_password">Password</label>
  <input type="password" name="password" id="id_password" required>
  <br/><br/>

  <input type="submit" value="Login" />

{% if user.is_authenticated %}
    <a href="{% url 'user_auth:logout' %}">Logout</a>
{% endif %}


</form>

user_auth/templates/authentication/user.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
          crossorigin="anonymous">
    <meta charset="utf8"/>
    <title>Login Welcome</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<h1> Welcome, {{username}} </h1>

<p> Your password is {{password}}</p>